version: '2.13.0'
services:
  simpleubuntu:
    container_name: mycontainer
    command: python3 -m http.server 1234
    ports:
    - 1234:1234
    build:
      context: .
      dockerfile: Dockerfile